global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'vue_app'
    static_configs:
      - targets: ['vue_app:9001']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
