name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Виконується на основній гілці

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Клонування репозиторію
    - name: Checkout repository
      uses: actions/checkout@v3

    # Встановлення Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Встановлення залежностей та збірка проєкту
    - name: Install and build
      run: |
        npm install
        npm run build

    # Архівування збірки
    - name: Archive production build
      run: |
        tar -czf dist.tar.gz dist

    # Запуск локальних контейнерів для Prometheus і Grafana
    - name: Setup Docker Compose for Prometheus and Grafana
      run: |
        # Створення Docker Compose файлу
        echo "
        version: '3'
        services:
          prometheus:
            image: prom/prometheus:latest
            container_name: prometheus
            ports:
              - 9090:9090
            volumes:
              - ./prometheus.yml:/etc/prometheus/prometheus.yml

          grafana:
            image: grafana/grafana:latest
            container_name: grafana
            ports:
              - 3000:3000
            environment:
              - GF_SECURITY_ADMIN_PASSWORD=admin
            depends_on:
              - prometheus
            networks:
              - monitoring

        networks:
          monitoring:
            driver: bridge
        " > docker-compose.yml

        # Створення файлу конфігурації Prometheus
        echo "
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'vuejs-app'
            static_configs:
              - targets: ['host.docker.internal:80']
        " > prometheus.yml

        # Запуск контейнерів
        docker-compose up -d

    # Зупинка контейнерів після завершення роботи
    - name: Stop Docker containers
      run: |
        docker-compose down

